# Generated by Django 3.1.5 on 2021-01-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
